class OffLineException implements Exception{}
class WrongdataExceeption implements Exception{}
class NotValidEmailException implements Exception{}
class NotValidPasswordException implements Exception{}
class NotValidDataExcption implements Exception{}
class EmptyUserException implements Exception{}
class EmptyMessageException implements Exception{}
class LocationPermissionException implements Exception{}
class LocationServiceException implements Exception{}
