name: chatapp
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  firebase_storage: ^12.2.0
  firebase_messaging: ^15.1.0
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.15.0
  permission_handler: ^11.3.1
  flutter_sound: ^9.11.2
  audioplayers: ^6.1.0
  dartz: ^0.10.1
  get_it: ^7.6.7
  internet_connection_checker: ^2.0.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.1
  lottie: ^3.1.2
  cached_network_image: ^3.4.0
  intl: ^0.18.1
  swipe_to: 1.0.6
  emoji_picker_flutter: ^2.0.0
  location: ^6.0.2
  google_maps_flutter: ^2.7.0
  file_picker: ^7.1.0
  syncfusion_flutter_pdfviewer: ^27.1.53


  cupertino_icons: ^1.0.6
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/splash/chat.json
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: PTSerif
      fonts:
        - asset: assets/fonts/PTSerif-Regular.ttf
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
